// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	Fullname        string             `json:"fullname"`
	Password        string             `json:"password"`
	Role            string             `json:"role"`
	Enable          int32              `json:"enable"`
	CreatedDatetime time.Time `json:"created_datetime"`
	UpdatedDatetime time.Time        `json:"updated_datetime"`
}

type UserConnection struct {
	ID                     int32       `json:"id"`
	Username               string      `json:"username"`
	LastConnectionDateTime pgtype.Date `json:"last_connection_date_time"`
	LastActionDateTime     pgtype.Date `json:"last_action_date_time"`
	LoggedOnDateTime       pgtype.Date `json:"logged_on_date_time"`
	ExpiredDateTime        pgtype.Date `json:"expired_date_time"`
	SessionKey             string      `json:"session_key"`
	ClientDevice           string      `json:"client_device"`
	CreatedDatetime        pgtype.Date `json:"created_datetime"`
	UpdatedDatetime        pgtype.Date `json:"updated_datetime"`
}

type UserPool struct {
	Username             string `json:"username"`
	LoginRetryCount      int32  `json:"login_retry_count"`
	DuplicatedLoginCount int32  `json:"duplicated_login_count"`
}
